### PR TITLE
run as non-root uid

### LINKED ISSUE #55: allow running as non-root
It would be great to run the container as non-root, preferably as random-non-root (via ld-wrapper). That's necessary for restricted kubernetes (e.g. openshift).

If you agree, I can provide a patch.

### PR DESCRIPTION
**Pull request by ibotty**
fixes #55.

BTW: That commit uses even more layers. Is it worth it to consolidate all the RUN statements to only create a single layer?

### CODE REVIEW

**Comment by ibotty** [comment]
Any comments?

**Comment by robinparisi** [comment]
I was annoyed by permissions on my OSX and was unable to make it works with Nginx and PHP-FPM after hours of trying!

Thanks a lot!

**Comment by pierreozoux** [comment]
Sorry for the delay, can you look how other official projects do solve this issue?
I'd prefer if we don't reinvent the weel.
(or maybe you already did, in this case, can you point me to some example code?)

Thanks a lot for the contribution :)

**Comment by pierreozoux** [comment]
@juliencarnot what do you think?

**Comment by juliencarnot** [comment]
@pierreozoux I have no recommendation on this, I haven't researched the subject as I use piwik locally with log-import. Sounds interesting to look how other php apps with more expert docker maintainers proceed!

**Comment by ibotty** [comment]
Openshift (a Kubernetes distribution) enforces running images as random uid (unless configured not to), so they have to change quiet a few images/build new images. The approach I used here is the one that is used at these images.

The diff is pretty minimal, I have never seen another approach to that problem nor can I think of one.

Before releasing this change one has to test that old installations (with image running as root) will continue running with that change. I assume they should, but better be safe!

**Comment by pierreozoux** [comment]
@tianon what do you think of this approach?

**Comment by tianon** [comment]
I think the approach at runtime of gating the `chown` on the container starting as root is sane (and is the exact approach most other official images take), but I'm not entirely sold on the explicit `USER 33`, especially since the Apache variant will fail out-of-the-box with that (default configuration binds to port 80, which is "privileged").  I think https://github.com/moby/moby/issues/8460#issuecomment-312459310 is the best workaround I've seen for that issue (since "privileged ports" is pretty meaningless inside a private network namespace), but it is non-default _and_ requires a sufficiently recent kernel.

**Comment by J0WI** [comment]
superseded by #86

**Pull request closed without merging**
