### PR TITLE
changes refs from Piwik to Matomo and updates to 3.4

### PR DESCRIPTION
**Pull request by juliencarnot**
In order to [pick up version 3.4](https://github.com/matomo-org/docker/issues/92), changes the github organization and repo name, and contains a few improvements (link to official site in readme and fixes [deprecated Maintainer tags](https://docs.docker.com/engine/reference/builder/#maintainer-deprecated)

### CODE REVIEW

**Comment by patte** [comment]
any chance 3.4 gets released on docker-hub today? I'm stuck with a 3.3 docker image, for a machine that run the 3.4 update manually over the web ui. matomo won't start anymore `NOTICE: PHP message: Error in Matomo: Your Matomo codebase is running the old version 3.3.0 and we have detected that your Matomo Database has already been upgraded to the newer version 3.4.0.`

**Comment by juliencarnot** [comment]
@patte : not sure if the 3.4 will be picked yet, looks like we need a few more steps in the docker hub repo for that: https://github.com/docker-library/official-images/pull/4196

If you need the 3.4 image, you can build it from the dockerfile in the meantime:
- fpm: https://raw.githubusercontent.com/matomo-org/docker/master/fpm/Dockerfile
- apache: https://raw.githubusercontent.com/matomo-org/docker/master/apache/Dockerfile

**Comment by patte** [comment]
@juliencarnot thank you very much for the prompt reply. I built as you recommended: https://hub.docker.com/r/patte8/piwik/
and our piwik is up and running again 👍

**Comment by yogabbagabb** [comment]
@patte 

Can you help me understand the error you received [here](https://github.com/matomo-org/docker/pull/93#issuecomment-379753456)?

I encountered the same error that you cane across:

```Your Matomo codebase is running the old version 3.3.0 and we have detected that your Matomo Database has already been upgraded to the newer version 3.4.0.```

What caused the database version to leap ahead of the Matomo codebase? Does this process happen automatically?

**Pull request merged**
