### PR TITLE
added unifont required for international instances

### PR DESCRIPTION
**Pull request by baywet**
this work also supports the azure offering CC @mattab

### CODE REVIEW

**Comment by mattab** [comment]
Refs: https://matomo.org/faq/how-to-install/faq_142/

**Comment by J0WI** [comment]
I'd prefer using the package from distros. Is this possible with Matomo?

**Comment by baywet** [comment]
Maybe @mattab can help answering this one

**Comment by J0WI** [comment]
For the reference:
https://packages.debian.org/stretch/all/ttf-unifont/filelist
https://pkgs.alpinelinux.org/contents?branch=v3.9&name=unifont&arch=s390x&repo=main

**Comment by baywet** [comment]
hum so we'd install the unifont package from the repos instead, good. @mattab can you give us an idea whether this should work or not?

**Comment by mattab** [comment]
It should work. as long as we can create a Symlink because the file needs to be found in `path/to/matomo/plugins/ImageGraph/fonts/unifont.ttf`

**Comment by baywet** [comment]
I'm not very familiar with the font system on Linux. Isn't there like a global registry on a system that applications can refer to?

**Pull request closed without merging**
