### PR TITLE
Rename to matomo

### PR DESCRIPTION
**Pull request by pierreozoux**
- [ ] PR official docker image to rename
 - [ ] PR official docker documentation to rename

### CODE REVIEW

**Comment by Silvenga** [comment]
I wonder if we should do something like "Matomo (formally Piwik)" for search engines - as least in a couple of locations.

**Comment by pierreozoux** [comment]
Do you mean just in the title or everywhere?

**Comment by Silvenga** [comment]
Maybe just in the title and into descriptions?

**Comment by pierreozoux** [comment]
Like this?

**Comment by crazy-max** [comment]
`(formerly Piwik)` would have made more sense no ?

**Comment by Silvenga** [comment]
Yeah something like that.

Facepalm, yeah, `formerly` is the correct spelling, thanks @crazy-max.

**Comment by pierreozoux** [comment]
@crazy-max @Silvenga I need an approval to merge that :)

**Comment by Silvenga** [comment]
Oops, sorry about that @pierreozoux.

**Comment by Silvenga** [comment]
Oh, just realized - want to delete `./logo.svg` in this pull?

**Comment by crazy-max** [comment]
@Silvenga Agree, no need to maintain this file or link it to the main repository maybe?

**Comment by pierreozoux** [comment]
Ah yes, the logo, good catch, I'll see when I PR the documentation, maybe I'll need to keep it.

**Pull request merged**
