### PR TITLE
Do not expose mysql (#118)

### PR DESCRIPTION
**Pull request by crazy-max**
And some coding style best practice

### CODE REVIEW

**Comment by mewm** [comment]
This broke the build however...

**Comment by crazy-max** [comment]
@mewm Can you explain pls ?

**Comment by mewm** [comment]
@crazy-max Looks like it got nothing to do with your changes, but some piwik docker images are missing: https://travis-ci.org/matomo-org/docker - more specifically 
```
The command "docker build -t piwik:fpm fpm" failed 3 times.
The command "travis_retry docker build -t piwik:fpm fpm" exited with 2.
0.05s$ ~/official-images/test/run.sh piwik:fpm
testing piwik:fpm
	image does not exist!
```

**Comment by crazy-max** [comment]
Yep not related at all, open a new issue. Thx

**Comment by mewm** [comment]
> Yep not related at all, open a new issue. Thx

Yeah sorry about that man, I wasn't trying to be an arsehole :P

**Pull request merged**
